spring:
  application:
    name: Tkitem-Backend
  datasource:
    url: ${ORACLE_DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}
  ai:
    retry:
      enabled: false
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: https://api.openai.com
      embedding:
        options:
          model: text-embedding-3-small   # 비용↓, 1536차원

logging:
  level:
    org.springframework.web.client: DEBUG
    org.apache.hc.client5.http: DEBUG
    org.apache.hc.client5.http.wire: DEBUG  # [주의] 매우 상세, 진단 끝나면 끄기


app:
  classify:
    batch-size: 500          # 1회 처리량 (조절)
    ambiguity-margin: 0.06   # top1-top2 마진 미만이면 '애매'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  address: 0.0.0.0


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: BATCH

swagger:
  server-url: ${SWAGGER_SERVER}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

kakao:
  api-key: ${KAKAO_API_KEY}

elastic:
  host: ${ELASTIC_HOST:localhost}
  port: ${ELASTIC_PORT:9200}
  scheme: ${ELASTIC_SCHEME:http}

#cloud:
#  aws:
#    s3:
#      bucket: ${AWS_S3_BUCKET}
#    stack:
#      auto: false
#    region:
#      static: ${AWS_REGION}
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}

#redis:
#  host: ${REDIS_HOST}
#  port: ${REDIS_PORT}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#
#  endpoint:
#    health:
#      show-details: always