spring:
  application:
    name: Tkitem-Backend
  config:
    import: optional:classpath:env.properties
  datasource:
    url: ${ORACLE_DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}
    hikari:
      connectionInitSql: "ALTER SESSION DISABLE PARALLEL DML"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}   # Gmail은 앱 비밀번호 필요
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  server-url: ${SWAGGER_SERVER}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

kakao:
  api-key: ${KAKAO_API_KEY}

cloud:
  aws:
    cdn:
      url: ${CDN_URL}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

redis:
  enabled: true
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

toss:
  secret-key: ${TOSS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#openai:
#  api-key: ${OPEN_AI_API_KEY}